1\. **PCA on 3D dataset**

* Generate a dataset simulating 3 features, each with N entries (N being ${\cal O}(1000)$). Each feature is made by random numbers generated according the normal distribution $N(\mu,\sigma)$ with mean $\mu_i$ and standard deviation $\sigma_i$, with $i=1, 2, 3$. Generate the 3 variables $x_{i}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues using the eigendecomposition of the covariance matrix
* Find the eigenvectors and eigenvalues using the SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained
* Redefine the data according to the new basis from the PCA
* Plot the data, in both the original and the new basis. The figure should have 2 rows (the original and the new basis) and 3 columns (the $[x_0, x_1]$, $[x_0, x_2]$ and $[x_1, x_2]$ projections) of scatter plots.

In [97]:
import numpy as np
import pandas as pd

from scipy import linalg as la
from matplotlib import pyplot as plt

In [98]:
import numpy as np
# construct a dataset with a skewed 2D distribution
mu = [0, 0] # centered on 0
sd = [1, 3] # Standard Deviation 

x1 = np.random.normal(mu[0], sd[0], 1000).T
x2 = x1 + np.random.normal(mu[1], sd[1], 1000).T
x3 = 2*x1 + x2

print("x1: \n", x1)
print("x2: \n", x2)
print("x3: \n", x3, "\n")

#creating a DataFrame with x1, x2 and x3

X = np.array([x1,x2,x3])
print("Our Dataset X: \n", X)


x1: 
 [-7.22859439e-01  4.89280192e-02  2.95660408e-01  7.34115092e-01
  1.85595779e-01  1.83208456e-01 -8.21501413e-01 -9.07852323e-01
 -4.09875161e-01 -1.78883038e-02 -1.72710392e-01  1.41581949e+00
 -3.76535989e-01 -1.59533392e+00  5.42159917e-01  2.75795797e+00
  1.09788991e+00  7.19597204e-02 -1.01817120e+00 -4.50780609e-01
 -1.12470182e+00 -8.22826304e-01  1.24603946e-01  5.19378519e-02
 -9.55039237e-01 -2.93618199e-01 -1.01137995e+00  1.33399999e+00
  8.03762859e-01 -8.17526036e-01  1.82502897e+00  1.37324378e+00
 -1.07681424e+00 -3.03526691e+00  1.10937626e+00 -1.40707755e+00
 -4.55616207e-01  1.12748096e-01 -3.05910769e-01  8.45857683e-01
  4.70499344e-01  5.70284906e-01 -1.40304258e+00  2.46112518e+00
 -3.36446084e-01  5.11080255e-01  7.07790421e-01  1.51056379e-01
 -1.05110794e+00 -6.84470920e-01 -1.76900549e-01  2.47775502e-01
 -2.16103825e+00  1.39097686e+00 -4.14759355e-01 -7.03926061e-01
  1.24812016e-01 -1.12858696e+00 -1.75309827e+00 -2.42163519e-01
  5.14670589e-01 -1

In [99]:
#Covariance of Matrix X
X_cov = np.cov(X)
print(X_cov)

l, V = la.eig(X_cov)
# the eigenvalues
print("The Eigen Values l:\n", l, '\n')
print("real(l):\n", np.real_if_close(l), '\n')
# V is the matrix of the eigenvectors
print("The Eigen Vectors V:\n", V, '\n')

[[ 1.03291913  1.12077772  3.18661598]
 [ 1.12077772 11.32482068 13.56637612]
 [ 3.18661598 13.56637612 19.93960808]]
The Eigen Values l:
 [3.02245676e+01+0.j 1.74737634e-15+0.j 2.07278027e+00+0.j] 

real(l):
 [3.02245676e+01 1.74737634e-15 2.07278027e+00] 

The Eigen Vectors V:
 [[-0.11021868 -0.81649658  0.56673201]
 [-0.58388344 -0.40824829 -0.70172178]
 [-0.80432081  0.40824829  0.43174224]] 



In [106]:
# To Find the eigenvectors and eigenvalues using the SVD. Check that the two procedures yield to same result

# perform the SVD
U, s, Vt = la.svd(X)
n=1000
print("shapes: U =", U.shape, "S:", s.shape, "V^T:", Vt.shape, '\n')
print("Spectrum:\n", s, '\n')
print("U:\n", U, '\n')
print("V^T:\n", Vt, '\n')
l_svd = s**2/(n-1)
V_svd = U

print("l: \n", l)
print("l_svd: \n", l_svd)
print("V: \n", V)
print("v_svd: \n", V_svd)
print("Are l and l_svd the same?", np.allclose(l, l_svd))
print("Are V and V_svd the same?", np.allclose(V, V_svd))

shapes: U = (3, 3) S: (3,) V^T: (1000, 1000) 

Spectrum:
 [1.73765268e+02 4.55136955e+01 1.54004991e-14] 

U:
 [[-0.11022154  0.56673146 -0.81649658]
 [-0.58387991 -0.70172472 -0.40824829]
 [-0.80432298  0.4317382   0.40824829]] 

V^T:
 [[ 1.91008650e-02 -8.84396504e-03  7.28512373e-03 ...  2.65260176e-02
  -3.07773997e-02 -1.79550474e-03]
 [-1.38414434e-02 -4.66997614e-03  1.68717254e-02 ...  2.62431892e-02
  -5.33401796e-02  2.88686526e-02]
 [-4.11221814e-01  8.31433031e-01  2.33417905e-03 ... -4.76346312e-03
   1.32407663e-02 -3.35894353e-03]
 ...
 [ 1.44100413e-02  1.72515451e-02 -2.39473801e-02 ...  9.98745546e-01
   1.86229218e-03 -6.14309208e-04]
 [-3.35225117e-02 -3.69234623e-02  2.44309542e-02 ...  2.07407124e-03
   9.96574504e-01  1.37844057e-03]
 [ 2.41604739e-02  1.59005293e-02 -4.69483063e-04 ... -7.07746520e-04
   1.47280087e-03  9.99175553e-01]] 

l: 
 [3.02245676e+01+0.j 1.74737634e-15+0.j 2.07278027e+00+0.j]
l_svd: 
 [3.02245930e+01 2.07357005e+00 2.37412785e-31]
V: 
 

In [110]:
Lambda = np.diag(l)
print("Lambda:\n", Lambda, '\n')
print("Trace(A):\n", X_cov.trace(), '\n')
print("Trace(Lambda):\n", Lambda.trace(), '\n')

print("By selecting the component 0, we retain %.2f%% of the total variability" % ((Lambda[0, 0]/Lambda.trace())*100))
X_new = np.dot(V_svd.T, X)

print("The new dataset is:\n", X_new)
print("\n The old dataset is:\n", X)

Lambda:
 [[3.02245676e+01+0.j 0.00000000e+00+0.j 0.00000000e+00+0.j]
 [0.00000000e+00+0.j 1.74737634e-15+0.j 0.00000000e+00+0.j]
 [0.00000000e+00+0.j 0.00000000e+00+0.j 2.07278027e+00+0.j]] 

Trace(A):
 32.29734789647814 

Trace(Lambda):
 (32.297347896478115+0j) 

By selecting the component 0, we retain 93.58% of the total variability
The new dataset is:
 [[ 3.31906693e+00 -1.53677396e+00  1.26590148e+00 ...  4.60930056e+00
  -5.34804311e+00 -3.11996362e-01]
 [-6.29975240e-01 -2.12547872e-01  7.67894574e-01 ...  1.19442452e+00
  -2.42770869e+00  1.31391907e+00]
 [ 2.22044605e-16 -1.11022302e-16  1.11022302e-16 ...  4.44089210e-16
  -4.44089210e-16 -5.55111512e-17]]

 The old dataset is:
 [[-0.72285944  0.04892802  0.29566041 ...  0.16887377 -0.78638937
   0.77902799]
 [-1.49586731  1.04644154 -1.27798505 ... -3.52943522  4.82619814
  -0.73984108]
 [-2.94158619  1.14429758 -0.68666423 ... -3.19168769  3.25341941
   0.8182149 ]]


C:\Users\Mahe\AppData\Local\Temp\ipykernel_4948\1959499545.py:6: ComplexWarning: Casting complex values to real discards the imaginary part
  print("By selecting the component 0, we retain %.2f%% of the total variability" % ((Lambda[0, 0]/Lambda.trace())*100))


2\. **PCA on a nD dataset**

* Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normally distributed, with a standard deviation much smaller (e.g. a factor 20) than those used to generate the $x_1$ and $x_2$. Repeat the PCA procedure and compare the results with what you have obtained before.

3\. **Optional**: **PCA on the MAGIC dataset**

Perform a PCA on the magic04.data dataset.

In [102]:
# get the dataset and its description on the proper data directory
# https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data 
# https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names 